Commands:
  reload: "&b&l[技能学习] &a➠ &f/ps reload 重载插件"
  open: "&b&l[技能学习] &a➠ &f/ps open <1-6槽位> 打开队伍中的1-6槽位精灵的技能学习界面"

Permission:
  reload: "pt.reload" #重置插件的权限名
  open: "pt.open" #帮打开学习技能界面的权限名

Messages:
  reload: "&b&l[技能学习] &a➠ &f重载成功!"
  noCommand: "&b&l[技能学习] &a➠ &f输入的指令有误!"
  noPermission: "&b&l[技能学习] &a➠ &f你没有该指令的权限!"
  noPlayer: "&b&l[技能学习] &a➠ &f输入该指令的不是一个玩家!"
  noPokemon: "&b&l[技能学习] &a➠ &f该槽位精灵不存在!"
  noEgg: "&b&l[技能学习] &a➠ &f该槽位精灵是蛋!"
  deleteSuccess: "&b&l[技能学习] &a➠ &f消耗学习之星成功!"
  deleteFail: "&b&l[技能学习] &a➠ &f你的学习之星不够!"

Settings:
  # 是否开启学习技能后精灵加入标签 "untradeable" "unbreedable"
  addFlag: true
  # 检测技能学习所需的道具的lore
  lore: "&f学习宝可梦技能的学习之星"
  # 一次消耗几个学习之星？
  num: 1
  # 是否开启相同技能名称过滤世代技能碟功能?
  sameName: true