Commands:
  reload: "&b&l[全服商店] &a➠ &f/yss reload 重载插件"
  open: "&b&l[全服商店] &a➠ &f/yss open <玩家> 打开玩家的全服商店界面"

Permission:
  reload: "yss.reload" #重置插件的权限名
  open: "yss.open" #帮打开界面的权限名

Messages:
  reload: "&b&l[全服商店] &a➠ &f重载成功!"
  noPermission: "&b&l[全服商店] &a➠ &f你没有该指令的权限!"
  noPlayer: "&b&l[全服商店] &a➠ &f输入该指令的不是一个玩家!"
  inputWrong: "&b&l[全服商店] &a➠ &f你输入的格式错误"
  noEco: "&b&l[全服商店] &a➠ &f你没有足够的金币!"
  noPoints: "&b&l[全服商店] &a➠ &f你没有足够的点券!"

  noPersonLimit: "&b&l[全服商店] &a➠ &f该商品已达你个人购买上限!"
  noServerLimit: "&b&l[全服商店] &a➠ &f该商品已达全服购买上限!"

  noPlayerPointsAPI: "&b&l[全服商店] &a➠ &f点券插件挂钩失败请通知服主!"
  noEconomy: "&b&l[全服商店] &a➠ &f金币插件挂钩失败请通知服主!"

Settings:
  # 是否启用yaml存储方式，不是的话就是启用数据库
  yaml: true
  # 刷新限制时间
  times: "3:30"

MySQL:
  #ip
  ip: "localhost"
  #端口
  port: "3306"
  #数据库名称
  database: "ServerStore"
  #用户名
  username: "root"
  #密码
  password: "123456"
  #驱动
  driver: "com.mysql.jdbc.Driver"
  #数据库表名
  tableName: "ServerStorePlayerData"
  #全服限购数据库表名
  serverLimitTableName: "ServerStoreServerLimit"
